### ISSUE TITLE
[LCD4Linux] Request

### ISSUE THREAD

**Issue by Varkentjes** [oe-alliance/oe-alliance-plugins#378]
In case of using service-name picons (SNP format). Is it possible to add a functionality to LCD4Linux so that the plugin automatically selects a picon without HD when no HD picon from a service is available? Such a function is already in Enigma2, so the picon is shown on the screen and in the webif, but in LCD4Linux the display remains blank.

Example: Select service SBS6 HD. In the absence of a picon for SBS6 HD, Enigma2 automatically selects the picon for SBS6.

**Comment by MrServo** [comment]
We're working on a new release for OpenATV 6.5 and we have complete that first. After that, we can have a look regarding your issue! Sorry for waiting so long.

**Comment by MrServo** [comment]
Hi Varkentjes,
I have verified the LCD4linux code and the fallback to SD-Picons have been carried out for the cases, that the servicereferences (and therefore the picons-filenames) are very similiar. Here an example:
'1_0_**19**_2840_41B_1_FFFF0000_0_0_0.png' for HD-picon of German station ""SWR RP HD""
'1_0_**1**_2840_41B_1_FFFF0000_0_0_0.png' for HD-picon of German station ""SWR RP""
In some cases the Servicereferences (and therefore the picons-filenames) are totally different, there is no solution programmed yet. But of course, this can be changed!  ;)
Please forward your belonging entries (only two lines) of your '**/etc/enigma2/lamedb5**' for your TV-station '**SBS6 HD**' and for '**SBS6**'. 
Kind regards.......Mr.Servo

**Comment by AbuBaniaz** [comment]
@Varkentjes is referring to picons which use the names , not the ones that use service references.

See here for the HD fall back.
https://github.com/OpenViX/enigma2/blob/Dev/lib/python/Components/Renderer/Picon.py#L97:L98

**Comment by MrServo** [comment]
@AbuBaniaz
Maybe the solution '**Piconname via lamedb5**' shall be taken over in **Picon.py : getPiconName()** ? In case this will be a good idea and will be implemented, I change LCD4Linux and use the getPiconName()...

**Comment by AbuBaniaz** [comment]
Yes, importing the picon name from picon.py would be best. No need to redo what has already been done.

**Comment by MrServo** [comment]
HiAbuBaniaz,
I totally agree with you, using **Picon.py:getPiconName()** will be the best solution for SNP and SRP!
But what ist about [issue #378](https://github.com/oe-alliance/oe-alliance-plugins/issues/378) of user **@Varkentjes**? It seems to me, that there are existing some troubles...?
It seems to me (and I can't find a solution in **Picon.py:getPiconName()**). Does the E2-code really meet his problem? It is true, that **LCD4Linux** don't use **getPiconName()** yet, but I see no "way-out". Maybe I am wrong, but what happens in case of different combination of  SRPs?
```
SRP of 'Erste HD':
1_0_19_2B5C_41B_1_FFFF0000_0_0_0.png daserstehd.png
with fallback to 'Das Erste':
1_0_1_6DCA_44D_1_FFFF0000_0_0_0.png daserste.png
```
Can you really ensure, that **Picon.py:getPiconName()** meet this issue? Please understand, that I will be very happy when **Picon.py:getPiconName()** will solve all possible problems...
BTW: What's about channel names with special characters? Shall we ask our users for posting their 'lamedb5' in order to catch all possible characters in channel names?
I'm sure that we solve that issue, aren't you?
Kind regards........Mr.Servo

**Comment by Huevos** [comment]
Service reference picon only fallback on field 0, or field 6. e.g...
4097_0_19_2B5C_41B_1_FFFF0000_0_0_0.png
1_0_19_2B5C_41B_1_FFFF0000_0_0_0.png

Service name picons only use ascii characters. Anything not in the character set is dropped.

Don't think about creating anything different because all picons are supplied according to the naming convention found in Picon.py.

**Comment by AbuBaniaz** [comment]
The original issue was related to Service Named Picons and the HD name fallback. If a person is using Service Reference picons, then they are not affected.

You can have a mixture of both, but SRP will have higher priority then SNP. I am referring to the coding in picon.py, not LCD4Linux.

I think it will be brilliant if you just import the name instead of  duplicating the process. After all, the picon.py code is already displaying the OSD picons without a problem.

**Comment by MrServo** [comment]
Thanks to you both!
You're right! Although 'Picon.py' is probably not equal for all images, I will remove my lamedb5-access and will use 'Picon.py' as an alternative supplier for piconnames (SRP/SNP) instead (as variable 'name5').

**Comment by MrServo** [comment]
please see new update v5.0-r8x
